### ISSUE TITLE
Jumping of div when play/pause button is clicked

### ISSUE THREAD

**Issue by Milstein** [rcc-uchicago/sankey#16]

**Comment by bkleeman** [comment]
Could this be because of the way the CSS `margin`, `border`, and `padding` properties change when you toggle between play and pause states?

### These are the dimensions when the animation is playing:
![image](https://user-images.githubusercontent.com/20052075/81410885-19b03b80-9107-11ea-9c43-28448b93f6c2.png)

### These are the dimensions when the animation is paused:
![image](https://user-images.githubusercontent.com/20052075/81411408-f2a63980-9107-11ea-86de-37694492e611.png)

### There is also a momentary change in these dimensions that happens for a split second in between play and pause states. It looks something like this but the values change depending on the state of the sankey animation above:
![image](https://user-images.githubusercontent.com/20052075/81411595-35681180-9108-11ea-9490-08b8f9696313.png)

**Comment by bkleeman** [comment]
We could hard code this class container:
![image](https://user-images.githubusercontent.com/20052075/81417950-93e5bd80-9111-11ea-9d2b-4c681ebf5472.png)

There is also a transition property on the button. If we deactivate that it may resolve the issue.
![image](https://user-images.githubusercontent.com/20052075/81418078-bed01180-9111-11ea-99ea-d76b12f90146.png)

**Comment by bkleeman** [comment]
We may be able to resolve by converting div button id="play-button" to a span instead of a button.
if we do this we may have to adjust whatever javascript is toggling the button to operate on a span instead of a button. if this results in cross-environment inconsistency, abandon the issue for now.

**Comment by bkleeman** [comment]
This SVG has viewbox height attribute that is causing it to overlap the play pause button. this is why you can only click the bottom portion. may be able to z-index the test tick box to the rear and position it relative. And then position relative the container div below it.
![image](https://user-images.githubusercontent.com/20052075/81419293-a8c35080-9113-11ea-95c3-ed2ba9c5cf5c.png)
